apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-checkpoint-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
