apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: stream-detection-echo
spec:
  image: stream-detection-java:spec1
  imagePullPolicy: Never
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "invest-kafka-kafka-bootstrap.kafka.svc:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/stream-detection.jar
    entryClass: com.invest_view.stream_detection.EchoJob
    parallelism: 1
    upgradeMode: stateless
