apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-service-config
  labels:
    app: alert-service
data:
  ALERT_SERVICE_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  ALERT_SERVICE_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  ALERT_SERVICE_AVRO_SCHEMA_PATH: "/app/schemas/stock-alerts.avsc"
  ALERT_SERVICE_KAFKA_TOPIC: "stock-alerts"
  ALERT_SERVICE_KAFKA_CONSUMER_GROUP: "alert-service-v1"
