apiVersion: v1
kind: ConfigMap
metadata:
  name: event-pattern-persistence-config
  labels:
    app: event-pattern-persistence
data:
  EVENT_PATTERN_PERSISTENCE_KAFKA_BOOTSTRAP_SERVERS: "invest-kafka-kafka-bootstrap.kafka.svc:9092"
  EVENT_PATTERN_PERSISTENCE_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  EVENT_PATTERN_PERSISTENCE_KAFKA_TOPIC: "stock-patterns"
  EVENT_PATTERN_PERSISTENCE_KAFKA_CONSUMER_GROUP: "event-pattern-persistence-v1"
  EVENT_PATTERN_PERSISTENCE_AVRO_SCHEMA_PATH: "/app/schemas/stock-patterns.avsc"
  EVENT_PATTERN_PERSISTENCE_LOG_LEVEL: "INFO"
